version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONPATH=/app

  whatsapp_bot:
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    command: uvicorn whatsapp_bot:app --host 0.0.0.0 --port 8001 --reload
    environment:
      - PYTHONPATH=/app